env:
  node: true
extends:
  - airbnb-base
  - prettier
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  prettier/prettier: error
  no-console: off
  import/extensions:
    - error
    - ignorePackages
    - js: always
plugins: [prettier]
